development:
  adapter: postgresql
  encoding: unicode
  database: codebeta_development
  pool: 5
  username: Gulnara
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: codebeta_test
  pool: 5
  username: Gulnara
  password: 